services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api/prod/Dockerfile
#    image: image_marina_api_prod
    volumes:
      - ./api:/var/www/api
    restart: always
#    container_name: marina_api_prod
    entrypoint: ['/bin/sh', '/install.sh']

  app:
    build:
      context: ./
      dockerfile: ./docker/app/prod/Dockerfile
    volumes:
      - ./app:/var/www/app
      - ./docker/app/prod/install.sh:/install.sh
    entrypoint: ["/bin/sh", "/install.sh"]

  admin:
    build:
      context: ./
      dockerfile: ./docker/admin/prod/Dockerfile
    volumes:
      - ./admin:/var/www/admin
      - ./docker/admin/prod/install.sh:/install.sh
    entrypoint: ["/bin/sh", "/install.sh"]
  
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/prod/Dockerfile
    volumes:
      - ./app:/var/www/app
      - ./admin:/var/www/admin
      - ./api:/var/www/api
      - ./docker/nginx/prod/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/prod/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./docker/nginx/prod/certificates/fullchain.pem:/var/www/certificates/gladkix.com/fullchain.pem
      - ./docker/nginx/prod/certificates/privkey.pem:/var/www/certificates/gladkix.com/privkey.pem

    ports:
      - "80:80"
      - "443:443"

  db:
    image: mysql:8.4
    restart: always
    volumes:
      - /home/gladkix/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: marina
      MYSQL_USER: marina
      MYSQL_PASSWORD: 1234
