nelmio_cors:
    defaults:
        origin_regex: true
#        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        # allow_origin: ['*']
        # allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        # allow_headers: ['*']
        # expose_headers: ['*']
        max_age: 3600
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['Accept', 'Accept-Encoding', 'Accept-Language', 'Connection', 'Content-Length', 'Content-Type', 'Host', 'Origin', 'Referer', 'sec-ch-ua', 'sec-ch-ua-mobile', 'sec-ch-ua-platform', 'Sec-Fetch-Dest', 'Sec-Fetch-Mode', 'Sec-Fetch-Site', 'User-Agent']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        expose_headers: ['*']
    paths:
        '^/': null
